### ISSUE TITLE
DmgCreator error with SpringToolSuite.munki.recipe

### ISSUE THREAD

**Issue by patgmac** [autopkg/rderewianko-recipes#16]
I get the following error with this recipe. First time running it so not sure if it worked before. Any idea what the cause might be? Download recipe seems to work as expected. 

Processing SpringToolSuite.munki.recipe...
creation of /Users/username/Library/AutoPkg/Cache/local.munki.SpringToolSuite/Spring Tool Suite.dmg failed: hdiutil: create failed - No such file or directory

Failed.

The following recipes failed:
    SpringToolSuite.munki.recipe
        Error in local.munki.SpringToolSuite: Processor: DmgCreator: Error: creation of /Users/username/Library/AutoPkg/Cache/local.munki.SpringToolSuite/Spring Tool Suite.dmg failed: hdiutil: create failed - No such file or directory

The following new items were downloaded:
    Download Path
    -------------
    /Users/username/Library/AutoPkg/Cache/local.munki.SpringToolSuite/downloads/Spring Tool Suite.dmg

**Comment by rderewianko** [comment]
seems macmule fixed this (guess i owe him a beer). i missed the issue.
