### ISSUE TITLE
Download page for PingID Mac client has changed

### ISSUE THREAD

**Issue by sdagley** [autopkg/rderewianko-recipes#20]
The previous DOWNLOAD_PAGE_URL of https://www.pingidentity.com/content/ping/en/resources/downloads/pingid.html is now a 404.

The new page looks to be: https://www.pingidentity.com/en/resources/downloads/pingid.html

**Comment by rderewianko** [comment]
Thanks! I've tested the download & the pkg with the new url.
As I don't work for Ping anymore, I don't actually utilize this repo anymore. Let me know if there's any other changes, i'm happy to make them
- RD
