### ISSUE TITLE
No match found

### ISSUE THREAD

**Issue by notverypc** [autopkg/rderewianko-recipes#6]
The download URL no longer matches
```No match found on URL: https://github.com//yakyak/yakyak/releases```

I've had a look but I can't see what has changed.

**Comment by rderewianko** [comment]
Thanks! I'm not too sure myself why it broke...
So I took the opportunity to update the recipes using the github processor (which should do a better job.)

You're going to have to update this repo on your autopkg/autopkgr instance, and then re-update the trust.

Using a command like: 
>autopkg update-trust-info /Users/<username>/Library/AutoPkg/RecipeOverrides/YakYak.jss.override.recipe

 The file name could be different depending what you're calling them.

**Comment by notverypc** [comment]
Thanks for updating the recipes, the download works but unfortunately the munki recipe is broken.
I get the following error when running my override or when running your recipe:
`creating pkginfo for /Volumes/Data/AutoPKG/Cache/local.override.munki.YakYak/YakYak.dmg failed: Could not find a supported installer item in /Volumes/Data/AutoPKG/Cache/local.override.munki.YakYak/YakYak.dmg!`

I'll try having a look.

**Comment by rderewianko** [comment]
I'll work on getting an updated one. I don't actively have a monkey
install. Feel free to hit me up on slack if you'd like to assist.

**Comment by notverypc** [comment]
Hey
I think I've fixed it or at least got it working. 
I've edited the following line:

```
<key>dmg_root</key>
<string>%RECIPE_CACHE_DIR%/%NAME%/Applications/YakYak-darwin-x64/</string>
```
I've upload a gist of the full recipe here: https://gist.github.com/notverypc/9bfddbb2996a41c12b6391d6acd15145

**Comment by rderewianko** [comment]
That'll work, however it ends up in a sub folder in the applications folder.

Its fine for now. I'll plan on building out a munki instance this week and see about getting it in the /Applications

**Comment by notverypc** [comment]
In my limited testing munki is installing YakYak correctly into /Applications  no sub folders.

**Comment by rderewianko** [comment]
Ah even better! I've updated the recipe with your gist. Thanks!
