### ISSUE TITLE
Spring Tool Suite app name change

### ISSUE THREAD

**Issue by smashism** [autopkg/rderewianko-recipes#8]
Clearly these people are yolo but the app appears to be called either Spring Tool Suite 4 or SpringToolSuite4, not STS.app. So the recipes for this are failing. I'm unsure about the actual app name and am hesitating to do a PR because it seems to download as either the name without spaces or the name with spaces and I'm unsure which they're actually going to go with.

**Comment by rderewianko** [comment]
It seems they change it by build. I'll update the recipe.

**Comment by rderewianko** [comment]
Updated the name and identifier.
